### PR TITLE
Added 2 icons, RVjack-extend and RVjack-retract for RVers 

### PR DESCRIPTION
**Pull request by goldriver2**

### CODE REVIEW

**Review by elax46 — CHANGES_REQUESTED** [review]
the name of the icons must be lowercase

**Comment by goldriver2** [comment]
Letters have been changed to lowercase

**Review by elax46 — CHANGES_REQUESTED** [review]
Sorry, I didn't explain myself, the change must be made in the `js` file

**Comment by elax46** [comment]
The requested changes have not been made, it's been a long time, so I'm closing it

**Pull request closed without merging**
