### PR TITLE
Added VRT radio station logos + virginmedia

### PR DESCRIPTION
**Pull request by thomasdg**
Added VRT Studio Brussels (vrt-stubru), VRT Klara (vrt-klara) and VRT Radio 1 (vrt-radio1).

### CODE REVIEW

**Review by elax46 — CHANGES_REQUESTED** [review]
PR requests should be directed to the dev branch, read the documentation, thanks

**Comment by thomasdg** [comment]
> PR requests should be directed to the dev branch, read the documentation, thanks

Sorry, first time trying ;)
Hope I fixed it now... Otherwise I will make a new pull request.

**Comment by elax46** [comment]
There are too many overlaps I advise you to reopen the request by making the changes starting from the dev branch

**Comment by rchiileea** [comment]
just wait for me I am back home soon

**Pull request closed without merging**
