### PR TITLE
add m/monit icon

### PR DESCRIPTION
**Pull request by victorclaessen**
Add the [logo](https://mmonit.com/monit/img/MonitLogo.png) for [m/monit](https://mmonit.com/).

### CODE REVIEW

**Comment by elax46** [comment]
hi from my point of view the pr is wrong you made the request in the main branch it should be made in the dev branch. For the correctness of the icon I leave the word @rchiileea

**Comment by victorclaessen** [comment]
> hi from my point of view the pr is wrong you made the request in the main branch it should be made in the dev branch. For the correctness of the icon I leave the word @rchiileea

I'm sorry I missed that last line in the readme. I rebased the pull request.

**Comment by elax46** [comment]
there are too many errors I recommend you resubmit the request

**Comment by victorclaessen** [comment]
> nope its over the border within the 24x24 box, you need to reed the submition rules

I'm sorry. I did read the submission rules, but perhaps I did not fully understand?
The largest number I see in the svg code is 23.937677. Does that not imply that it fits inside a 24x24 box?
Could you help me by making more clear what I did wrong?

I will then resubmit.

**Comment by victorclaessen** [comment]
ChatGPT thinks it's ok 🤷‍♂️  .

image

**Comment by rchiileea** [comment]
you are right, from the look of it a pull previously has been removed that tells people they must leave a 2 px width around the icon all sides withing the 24x24 box @elax46 do you have any idea when this was removed from the readme? via someone elses pull?

**Comment by elax46** [comment]
> you are right, from the look of it a pull previously has been removed that tells people they must leave a 2 px width around the icon all sides withing the 24x24 box @elax46 do you have any idea when this was removed from the readme? via someone elses pull?

I don't know, maybe it was overwritten in some pulls.  Do a pull again specifying the redme of the question

**Pull request closed without merging**
