### PR TITLE
Rangerover

### PR DESCRIPTION
**Pull request by a-r-j-a-n**
Added range rover icon

### CODE REVIEW

**Review by elax46 — CHANGES_REQUESTED** [review]
Your previous request #672 was canceled push request as I didn't notice that the wrong branch was selected. I invite you to read the insertion rules for this reason.

Regarding this request:

1. You cannot insert the authorship on the entire Car Manifattura block, yours is only one icon, all the rest were made by @rchiileea 
2.The range-rover icon is not the correct size in the svg as the viewbox is missing
3. The fourt icon cannot have a specific section as it is a single icon and is not part of a brand or block of icons and therefore must be included in Miscellany of Icons

**Comment by rchiileea** [comment]
@a-r-j-a-n  is this not the second icon you have submitted as a pull request that is wrong? Please be patient as mentioned in the refused quat one needs to be a 24x24 view box with a 2pixel bleed area around the icon.

**Comment by a-r-j-a-n** [comment]
I dont understand what the issue with the viewbox is for the rangerover svg.

image

Here it says the viewbox is 0 0 24. Can you please explain?

**Comment by rchiileea** [comment]
you deleted 150x150 and added 150 x 150, I have checked the quatt logo its fine, what are you using to create icons?

**Comment by rchiileea** [comment]
see this post for a discription, maybe also try not to mess up the readme, but this should help you https://github.com/elax46/custom-brand-icons/pull/665#issuecomment-2135788285

Also I would rather you clean up the range rover icon as its a bit janky (odd edges and more points than needed.

**Comment by a-r-j-a-n** [comment]
I was using [boxy-svg.com/app](https://boxy-svg.com/app) for the logo's.

For now, I will not continue the Range Rover logo. Maybe later I will create one that is not so janky. This one was created using an already existing svg file with the odd edges.

I will create a new pull request only for the Quatt logo in the misc table. That's the one I need now.

**Comment by rchiileea** [comment]
I added the quart logo myself for next release and elax will sort  it out

**Pull request closed without merging**
