### PR TITLE
Add Miscellany icons

### PR DESCRIPTION
**Pull request by ivomarsan**
### Refact:
* Disney Plus
* HBO Max
* Netflix
* Prime Video

### Create:
* Star Plus
* Twitch
* Xbox
* DirectvGO
* Youtube
* Alternative icons for
  * Disney Plus
  * HBO Max
  * Netflix
  * Prime Video

### Organize:
* Converted Avaliable Icons table from 2 columns to 1, because some icons was hidden. This change avoid similar wrong includes because improve the pattern, making more easy
* Reordered alfabetically in ASC mode, to keep more organized.

### Optimizations:
* Fixed some icons viewbox from "0 0 24000 24000" to "0 0 24 24", decreasing the file size.

Helpfull tool: https://jakearchibald.github.io/svgomg/

### CODE REVIEW

**Comment by elax46** [comment]
You did a great job but when it comes to the icon table in the past it was structured like this because the icons were few with many icons you have to scroll the page a lot, what do you think of this change @rchiileea ?

**Comment by rchiileea** [comment]
it looks good to me apart from the the new icon for you tube as one of the std mdi icons is basically youtubes icon almost a carbon copy mid:youtube is basically spot on and would be silly to create the same one in repo with out over fancifying it and adding lots of code to make it fancy... I can do it if you want.

**Review by elax46 — CHANGES_REQUESTED** [review]
The youtube icon is already present in the mdi archive so it is useless to insert it here. In order not to make the README.md too long, the best arrangement is two columns

**Comment by ivomarsan** [comment]
> The youtube icon is already present in the mdi archive so it is useless to insert it here. In order not to make the README too long, the best arrangement is two columns

Ok, I'll convert to two columns. But as one column we have more easily asc ordenation. But I'll do it!

**Comment by ivomarsan** [comment]
Converted to One Column
Reordered by ASC
Converted to Two Columns

@elax46 @rchiileea https://github.com/elax46/custom-brand-icons/pull/239/commits/b51d280d30c1af2dae5b1b35ad61d8b460b0afdd

**Review by elax46 — CHANGES_REQUESTED** [review]
The old version of `README `still appears in the pull

**Comment by rchiileea** [comment]
Xbox is also a mdi default icon :)

but here are the others 

image
image
image
image
image
image
image
[06-09-22-part2.zip](https://github.com/elax46/custom-brand-icons/files/9498903/06-09-22-part2.zip)

**Comment by elax46** [comment]
> Xbox is also a mdi default icon :)
> 
> but here are the others
> 
> image image image image image image image [06-09-22-part2.zip](https://github.com/elax46/custom-brand-icons/files/9498903/06-09-22-part2.zip)

If @ivomarsan  makes the changes I approve its commit so I won't use your @rchiileea  icons otherwise we integrate these

**Comment by ivomarsan** [comment]
> The old version of `README` still appears in the pull

Sorry for this. I fixed now!

**Pull request merged**
