### PR TITLE
Add Cowboy logo

### PR DESCRIPTION
**Pull request by gurtjun**

### CODE REVIEW

**Comment by rchiileea** [comment]
this wont be approved that code is way to long for a icon, our file is large already this code is 30x the size of some of the most complicated icons in the repo.  please make a request instead

**Comment by rchiileea** [comment]
@elax46 reject this pull request icons as they are unneciserry to big for what they are.

**Comment by gurtjun** [comment]
> this wont be approved that code is way to long for a icon, our file is large already this code is 30x the size of some of the most complicated icons in the repo. please make a request instead

Ok, I need to check how I can make them smaller…

**Comment by gurtjun** [comment]
@rchiileea / @elax46 I removed the IKEA one (that's indeed very large). Can you please check the Cowboy ones again? They are not as big compared to other icons.

**Comment by rchiileea** [comment]
> @rchiileea / @elax46 I removed the IKEA one (that's indeed very large). Can you please check the Cowboy ones again? They are not as big compared to other icons.

They still seem a bit large to me for what effectively are a  30 point icon for the plain one and a 38 point one for the second. Sorry it’s just I have mad lots of icons now and I can generally tell from code if there are to many points, but a request in for both in issues, both the ikea and the cowboy I am sure I can throw something hing together for the next release

**Comment by gurtjun** [comment]
> > @rchiileea / @elax46 I removed the IKEA one (that's indeed very large). Can you please check the Cowboy ones again? They are not as big compared to other icons.
> 
> They still seem a bit large to me for what effectively are a 30 point icon for the plain one and a 38 point one for the second. Sorry it’s just I have mad lots of icons now and I can generally tell from code if there are to many points, but a request in for both in issues, both the ikea and the cowboy I am sure I can throw something hing together for the next release

Do you want me to provide the image files via issues? SVG files were generated using Inkscape (but I don't have any experience with that so must have done something wrong)

**Comment by elax46** [comment]
you can open a request for new icons @rchiileea  will take care of it I'll close this request

**Comment by rchiileea** [comment]
> > > @rchiileea / @elax46 I removed the IKEA one (that's indeed very large). Can you please check the Cowboy ones again? They are not as big compared to other icons.
> > 
> > 
> > They still seem a bit large to me for what effectively are a 30 point icon for the plain one and a 38 point one for the second. Sorry it’s just I have mad lots of icons now and I can generally tell from code if there are to many points, but a request in for both in issues, both the ikea and the cowboy I am sure I can throw something hing together for the next release
> 
> Do you want me to provide the image files via issues? SVG files were generated using Inkscape (but I don't have any experience with that so must have done something wrong)

my main issue is SVG if none exists share picture, but I wont click any links in posts thanks to one person linking a svg that was on a site known for breaches... so I must see a image in the post.

https://github.com/elax46/custom-brand-icons/issues you request here, but make sure to read the guidlines for this when you do it in the future, I have added these icons for next release (redone them)

**Comment by rchiileea** [comment]
cowboy-ebike
cowboy-ebike-alt
ikea-sinnerlig

**Comment by gurtjun** [comment]
> cowboy-ebike cowboy-ebike-alt ikea-sinnerlig

Thanks! Looks nice

**Pull request closed without merging**
