### PR TITLE
Update CONTRIBUTING.md to include icon specifications

### PR DESCRIPTION
**Pull request by Gtt1229**
Does the updated wording convey the specifications described in https://github.com/elax46/custom-brand-icons/discussions/753 ?

I was going back in forth between:

```
The size of the image must be 24px by 24px
```
or
```
The size of the viewbox must be 24px by 24px
```
or
```
The size of the canvas must be 24px by 24px
```

### CODE REVIEW

**Comment by Gtt1229** [comment]
Will also have to update readme

**Comment by rchiileea** [comment]
remove image as its confusing for people that dont deal with SVG's normally.

I would put

the size of the view box must be 24x24

the size of the icon in view box must be 20x20,

 ill give you an example of the sillyness it can cause, take the ike one, when redownloaded it had resized it self to 15x15, but it can go both ways it can resize itself upto 3000x3000 which we have had previously.

**Review by rchiileea — CHANGES_REQUESTED** [review]
- The size of the icons must be **24px by 24px**. (change to The size of the SVG must be)
- The size of the viewbox must be   **24px by 24px**.
- The icon in the box must have a 2px border around it minumum and should not protrude into this area. 
-

**Review by rchiileea — CHANGES_REQUESTED** [review]
- The size of the icons must be **24px by 24px**. (change to The size of the SVG must be)
- The size of the viewbox must be   **24px by 24px**.
- The icon in the box must have a 2px border around it minumum and should not protrude into this area. 
 
again everything else looks fine apart from that wording

**Comment by Gtt1229** [comment]
https://github.com/elax46/custom-brand-icons/pull/768 created

**Pull request closed without merging**
