### PR TITLE
Added 12 TV channels icons

### PR DESCRIPTION
**Pull request by Pinky007**
Added 12 TV channels icons
Added new TV section for icons on readme
Reorganize some of the icons in miscellaneous to match the new TV section (may have missed some icons)
Added huawei icon and therefore cover half of https://github.com/elax46/custom-brand-icons/issues/297

### CODE REVIEW

**Comment by Pinky007** [comment]
@elax46 , let me know if I made more errors that the one in https://github.com/elax46/custom-brand-icons/pull/300
Should have started from the dev branch and changed color to #44739e.

**Review by elax46 — CHANGES_REQUESTED** [review]
Update the Readme file following the previously released update. Also #297 has been completed

**Comment by Pinky007** [comment]
Hej @elax46 , I updated the readme and with the new clean version and removed the huawei icon.
Let me know if there is anything else :)

**Review by elax46 — CHANGES_REQUESTED** [review]
There is a conflict in the check javascript file

**Review by elax46 — CHANGES_REQUESTED** [review]
There are still conflicts to resolve in

```
README.md
dist/custom-brand-icons.js
```

**Comment by Pinky007** [comment]
reversed my branch and recommited the changes.
Hopefully, this worked this time!

**Pull request merged**
